name = "server4"
main = "worker.js"
compatibility_date = "2026-01-06"

[[d1_databases]]
binding = "server"
database_name = "server"
database_id = "8d15e597-4b2d-4e66-974d-fc49073383fc"

[[r2_buckets]]
binding = "server2"
bucket_name = "server2"

[ai]
binding = "AI"
